import numpy as np
import matplotlib.pyplot as plt
data = np.loadtxt("populations.txt")
year, hares, lynxes, carrots = data.T
"""plt.axes([0.2, 0.1, 0.5, 0.8])
plt.plot(year, hares, year, lynxes, year, carrots)
plt.legend(('Hare', 'Lynx', 'Carrot'), loc=(1.05, 0.5))
plt.show()"""
populations = data[:, 1:]
print("1.")
print("Mean of population of")
print("hares:" + str(populations.mean(axis=0)[0]) + " lynxes:" + str(populations.mean(axis=0)[1]) + " carrots:" + str(populations.mean(axis=0)[2]))
print("Std of population of")
print("hares:" + str(populations.std(axis=0)[0]) + " lynxes:" + str(populations.std(axis=0)[1]) + " carrots:" + str(populations.std(axis=0)[2]))
print("2.")
print("Which year each species had the largest population")
print("hares:" + str(int(year[hares.argmax()])))
print("lynxes:" + str(int(year[lynxes.argmax()])))
print("carrots:" + str(int(year[carrots.argmax()])))
print("3.")
print("Which species has the largest population for each year")
mas = np.array(['H', 'L', 'C'])
ind = np.argsort(data[:, 1:])
ind = ind.argmax(axis = 1)
print(mas[ind])
print("4.")
print("Which years any of the populations is above 50000")
ind = np.any(data[:, 1:] > 50000, axis = 1)
print(ind)
print("5.")
print("The top 2 years for each species when they had the lowest populations")
print("hares:" + str(int(year[np.argsort(hares)[0]])) + " and " + str(int(year[np.argsort(hares)[1]])))
print("lynxes:" + str(int(year[np.argsort(lynxes)[0]])) + " and " + str(int(year[np.argsort(lynxes)[1]])))
print("carrots:" + str(int(year[np.argsort(carrots)[0]])) + " and " + str(int(year[np.argsort(carrots)[1]])))
print("6.")
plt.plot(year, np.gradient(hares), year, np.gradient(lynxes))
plt.show()
print(np.corrcoef(np.gradient(hares), np.gradient(lynxes)))
